### ISSUE TITLE
Error in size & beaufort covariate plots?

### ISSUE THREAD

**Issue by stewartford** [dill/RDistanceBook#18]
Hi Dave

In the section "Adding and Selecting Covariates", immediately after plotting:

    plot(hn.dolphins.size.beaufort)

There is some discussion with a reference to the middle plot showing Beaufort state. But I've been following the code here and in the [book] (http://converged.yt/RDistanceBook/distance-covardf.html) and the middle plot displays the effect of group size, unless I'm interpreting it incorrectly.  The right hand plot displays beaufort.  

A potentially separate issue - the lines in the middle and right hand plots look identical, and the legend shows Beaufort 1, 3, <b>3</b> not 1, 3, 5.

Cheers

Stewart

**Comment by dill** [comment]
Thanks for spotting this Stewart! You are right, there is something odd going on here and I believe the two are linked.

It looks like there is a problem in my plotting code. I'm in the midst of preparing for a workshop at the moment, but I'll come back to this when I get a chance in early November at the latest. Sorry for the delay.

**Comment by stewartford** [comment]
No problem Dave. I was really hoping to make it to the workshop but can't this time round.  I hope it's productive.

Cheers 

Stewart

**Comment by dill** [comment]
Sorry for the delay in coming back to this...

Looks like there a few things going on there!

* The label was wrong for what was there (BUT it should have been right and was wrong because of other bugs)
* Beauort sea state was being included as a continuous covariate, rather than factor
* Plotting code was only plotting the first covariate level set over and over.

I've fixed these in `Distance2` and on the book website.

Thanks again for taking the time to report these errors, and please do report other problems that you come accross!

(Fixed in 7e088e3 and 1ebe2b2, see also `Distance2`.)
